### ISSUE TITLE
[WIP] Host a panel about neurodiversity and invisible disabilities

### ISSUE THREAD

**Issue by nickttng** [A11YChi/meetups-and-events#1]
**Why:** As an attendee, I want to learn more about invisible disabilities and how we can work with them to create an more inclusive experience

## ToDo

**30 days before the event**
- [x] Identify potential panelists
  - [x] Panelist 1 - KC (see confirmation below)
  - [x] Panelist 2 - FS
  - [x] Panelist 3 - SC
- [x] Reach out to panelists
  - [x] **Confirmed**: Panelist 1 - "Have a degenerative cornea disease called keratoconus that causes vision loss"
  - [x] **Confirmed**: Panelist 2 - Check with identification
  - [x] **Confirmed**: Panelist 3 - Check with identification
- [x] Have a kick-off conversation
- [x] Coordinate with co-orgs for date availability
- [x] Coordinate with the panelists for next steps
  - [x] Get synopsis and bio
  - [x] Set potential dates
- [x] Secure ACS captioner
- [x] Create event page/URL

**15 days before the event**
- [x] Announce through channels (MTLS)
  - [x] Mailing list
  - [x] Twitter
  - [x] LinkedIn
  - [x] Web-A11Y Slack
- [x] Share event page/URL with panelists

**1-5 days before the event**
- [x] Reminders through channels (MTLS)
  - [x] Mailing list
  - [x] Twitter
  - [x] LinkedIn
  - [x] Web-A11Y Slack
- [x] Follow up with panelists for being online (5-10 before official "online") and any needs
- [x] Update housekeeping slides

**Day of event**
- [x] Co-orgs arrive in Zoom at 6pm CT
- [x] Coordinate with panelists
- [x] Announcements and talk

**1-5 days after the event**
- [x] Post-announcement, YouTube share, and thanks (MTLS)
  - [x] Shoutout for panelists
- [x] Finalize transcript and redact if needed for confidentiality 
  - [x] Get transcript from ACS
  - [x] Edit transcript and push to GitHub transcript repo

**Post-event (based on team bandwidth)**
- [x] Add transcript to YouTube video talk

**Comment by nickttng** [comment]
Finally, transcript is edited and captions have been added. Closing.
