### ISSUE TITLE
[Potential] Project Managers / Product Owners and Accessibility - ML

### ISSUE THREAD

**Issue by nickttng** [A11YChi/meetups-and-events#13]
Why: As an attendee who is a project manager or product owner, I am poorly equipped to assess whether accessibility is actually being addressed and want to learn how to remedy it.

## ToDo

**30 days before the event**
- [x] Co-org to reach out to presenter
- [ ] Have a kick-off conversation
- [ ] Coordinate with co-orgs for date availability
- [ ] Coordinate with the presenter for next steps
  - [ ] Get synopsis and bio
  - [ ] Set potential dates
  - [ ] Share 'Accessible Presentation' guideline
- [ ] Secure ACS captioner
- [ ] Create event page/URL

**15 days before the event**
- [ ] Announce through channels (MTLS)
  - [ ] Mailing list
  - [ ] Twitter
  - [ ] LinkedIn
  - [ ] Web-A11Y Slack
- [ ] Share event page/URL with venue and presenter
- [ ] If feasible, request (rough) slides from presenter for _initial_ accessibility check

**1-5 days before the event**
- [ ] Reminders through channels (MTLS)
  - [ ] Mailing list
  - [ ] Twitter
  - [ ] LinkedIn
  - [ ] Web-A11Y Slack
- [ ] Soft check with venue for anything needed
- [ ] Follow up with presenter for being online (5-10 before official "online") and any needs
- [ ] Update housekeeping slides
- [ ]  Presenter's slides
  - [ ] Request slides from presenter for _final_ accessibility check
  - [ ] Send presenter's slides to ACS

**Day of event**
- [ ] Co-orgs are in video meeting 5-10 minutes to discuss any needs/issues before the official "online" for attendees
- [ ] Coordinate with presenter
- [ ] Announcements and talk

**1-5 days after the event**
- [ ] Post-announcement, YouTube share, and thanks (MTLS)
  - [ ] Shoutout for presenter
- [ ] Finalize transcrit
  - [ ] Get transcript from ACS
  - [ ] Edit transcript and push to GitHub transcript repo

**Post-event (based on team bandwidth)**
- [ ] Add transcript to YouTube video talk
