### ISSUE TITLE
[Completed] Focus style - EB

### ISSUE THREAD

**Issue by nickttng** [A11YChi/meetups-and-events#14]
**Why:** As an attendee / designer, I want to learn about how to effectively design and implement accessible focus styles

Slides: [_If It's interactive, it needs a focus style_](https://noti.st/ericwbailey/TcMJFP/if-its-interactive-it-needs-a-focus-style)

## ToDo

**30 days before the event**
- [x] Co-org to reach out to presenter
- [x] Have a kick-off conversation
- [x] Coordinate with co-orgs for date availability
- [x] Coordinate with the presenter for next steps
  - [x] Get synopsis and bio
  - [x] Set potential dates
  - [x] Share 'Accessible Presentation' guideline
- [x] Secure ACS captioner
- [x] Create event page/URL

**15 days before the event**
- [x] Announce through channels (MTLS)
  - [x] Mailing list
  - [x] Twitter
  - [x] LinkedIn
  - [x] Web-A11Y Slack
- [x] Share event page/URL with venue and presenter
- [x] If feasible, request (rough) slides from presenter for _initial_ accessibility check

**1-5 days before the event**
- [x] Reminders through channels (MTLS)
  - [x] Mailing list
  - [x] Twitter
  - [x] LinkedIn
  - [x] Web-A11Y Slack
- [x] Follow up with presenter for being online (5-10 before official "online") and any needs
- [x] Update housekeeping slides
- [x]  Presenter's slides
  - [x] Request slides from presenter for _final_ accessibility check
  - [x] Send presenter's slides to ACS
- [x] Add to Speakerdeck (and correct YouTube link on the site)

**Day of event**
- [x] Co-orgs are in video meeting 5-10 minutes to discuss any needs/issues before the official "online" for attendees
- [x] Coordinate with presenter
- [x] Announcements and talk

**1-5 days after the event**
- [x] Post-announcement, YouTube share, and thanks (MTLS)
  - [x] Shoutout for presenter
- [x] Have a retrospective with co-org team: 1) What went well; 2) What didn't go well; and 3) What improvements can we make next time?
- [x] Finalize transcript
  - [x] Get transcript from ACS
  - [x] Edit transcript and push to GitHub transcript repo

**Post-event (based on team bandwidth)**
- [ ] Add live-captioning to YouTube video talk

**Comment by nickttng** [comment]
Since this event is completed, we are closing this issue.
