### ISSUE TITLE
[Potential] Host an online panel re: A11y and Inclusive Design in EdTech tools

### ISSUE THREAD

**Issue by nickttng** [A11YChi/meetups-and-events#15]
**Why:** As an attendee who works in EdTech and/or involved in education, e.g. teachers/staff, I want to learn about creating accessible products.

**Who's involved:** SD/AC from EB company, A11YChi, potential local EdTech groups, teachers as one of a panel, etc.

Working info:

- **Title**: Inclusive Design in Education Technology (EdTech)
- **Synopsis:** An expert panel engages in a discussion at the intersection of education, design, and inclusivity
  -  Planning for different learning types, including multi-sensory learners, kinesthetic learners, and those with accessibility needs
  - Approaching systemic challenges: what does it mean to design for the achievement gap or the digital divide
  - How can product designers connect with teachers and other users to make more successful products? 

---

## ToDo

**30 days before the event**
- [x] Have a kick-off conversation with SD/AC
- [x] SD/AC hone and send panel title/theme and synopsis to Nick
- [ ] Coordinate with co-orgs for date availability
- [ ] Coordinate with the presenter for next steps
  - [ ] Get synopsis and bio
  - [ ] Set potential dates
  - [ ] Share 'Accessible Presentation' guideline
- [ ] Secure ACS captioner
- [ ] Create event page/URL

**15 days before the event**
- [ ] Announce through channels (MTLS)
  - [ ] Mailing list
  - [ ] Twitter
  - [ ] LinkedIn
  - [ ] Web-A11Y Slack
- [ ] Share event page/URL with venue and presenter
- [ ] If feasible, request (rough) slides from presenter for _initial_ accessibility check

**1-5 days before the event**
- [ ] Reminders through channels (MTLS)
  - [ ] Mailing list
  - [ ] Twitter
  - [ ] LinkedIn
  - [ ] Web-A11Y Slack
- [ ] Soft check with venue for anything needed
- [ ] Follow up with presenter for being online (5-10 before official "online") and any needs
- [ ] Update housekeeping slides
- [ ]  Presenter's slides
  - [ ] Request slides from presenter for _final_ accessibility check
  - [ ] Send presenter's slides to ACS

**Day of event**
- [ ] Co-orgs are in video meeting 5-10 minutes to discuss any needs/issues before the official "online" for attendees
- [ ] Coordinate with presenter
- [ ] Announcements and talk

**1-5 days after the event**
- [ ] Post-announcement, YouTube share, and thanks (MTLS)
  - [ ] Shoutout for presenter
- [ ] Finalize transcript
  - [ ] Get transcript from ACS
  - [ ] Edit transcript and push to GitHub transcript repo

**Post-event (based on team bandwidth)**
- [ ] Add transcript to YouTube video talk
