### ISSUE TITLE
[WIP] Professional testers with disabilities - HB & JS

### ISSUE THREAD

**Issue by nickttng** [A11YChi/meetups-and-events#17]
**Why:** As an attendee, I want to learn how to work with professional testers with disabilities within our testing process.

- **Title:** TBD
- **Synopsis (Draft):** By making the digital world more accessible, it will create more opportunity for employment for individual with disabilities, by connecting developers with individuals with disabilities will make personal connections and understanding of accessibility, which will improve the accessibility of the digital world 
- **When:** Tuesday, June 9 2020

---

## ToDo

**30 days before the event**
- [x] Co-org to reach out to presenter
- [x] Have a kick-off conversation
- [x] Coordinate with co-orgs for date availability
- [x] Coordinate with the presenter for next steps
  - [x] Get synopsis 
  - [x] Get bio
  - [x] Set potential dates
  - [x] Share 'Accessible Presentation' guideline
- [x] Request ACS captioner
- [x] Create event page/URL

**15 days before the event**
- [x] Announce through channels (MTLS)
  - [x] Mailing list
  - [x] Twitter
  - [x] LinkedIn
  - [x] Web-A11Y Slack
- [x] Share event page/URL with presenter
- [x] If feasible, request (rough) slides from presenter for _initial_ accessibility check
- [x] Secure ACS captioner

**1-5 days before the event**
- [x] Reminders through channels (MTLS)
  - [x] Mailing list
  - [x] Twitter
  - [x] LinkedIn
  - [x] Web-A11Y Slack
- [x] Follow up with presenter for being online (5-10 before official "online") and any needs
- [x] Update housekeeping slides
- [x]  Presenter's slides
  - [x] Request slides from presenter for _final_ accessibility check
  - [x] Send presenter's slides to ACS

**Day of event**
- [x] Co-orgs arrive in Zoom at 6pm CT
- [x] Coordinate with presenters
- [x] Announcements and talk

**1-5 days after the event**
- [ ] Post-announcement, YouTube share, and thanks (MTLS)
  - [ ] Shoutout for presenter
- [x] Finalize transcript
  - [x] Get transcript from ACS
  - [x] Edit transcript and push to GitHub transcript repo

**Post-event (based on team bandwidth)**
- [x] Add transcript to YouTube video talk

**Comment by nickttng** [comment]
This event is completed. 

Note: Equal Entry will do a blog recap, so keep an eye out for it.
