### ISSUE TITLE
[WIP] Testing Web Accessibility - AD

### ISSUE THREAD

**Issue by nickttng** [A11YChi/meetups-and-events#18]
**Why:** As an attendee, I want to learn how to use automated a11y tests as one step of a larger testing process.

- **Title:** Testing Web Accessibility
- **Synopsis:** Automated web a11y tests can free up our QA team from manual testing every part of our application…but…they can’t automatically, and magically, make our site accessible. We should use automated a11y tests as one step of a larger testing process
- **Primary audience:** Developers and/or engineers, especially front-end
- **Secondary audience:** Designers, product owners, anyone who works on digital and web products
- **When** Potentially, July or August
- **Notes:** Will have video demos; The speaker is based in Vienna, Austria

---

## ToDo

**30 days before the event**
- [x] Co-org to reach out to presenter
- [x] Have a kick-off conversation
- [ ] Coordinate with co-orgs for date availability
- [ ] Coordinate with the presenter for next steps
  - [ ] Get synopsis 
  - [ ] Get bio
  - [ ] Set potential dates
  - [ ] Share 'Accessible Presentation' guideline
- [ ] Secure ACS captioner
- [ ] Create event page/URL

**15 days before the event**
- [ ] Announce through channels (MTLS)
  - [ ] Mailing list
  - [ ] Twitter
  - [ ] LinkedIn
  - [ ] Web-A11Y Slack
- [ ] Share event page/URL with presenter
- [ ] If feasible, request (rough) slides from presenter for _initial_ accessibility check

**1-5 days before the event**
- [ ] Reminders through channels (MTLS)
  - [ ] Mailing list
  - [ ] Twitter
  - [ ] LinkedIn
  - [ ] Web-A11Y Slack
- [ ] Follow up with presenter for being online (5-10 before official "online") and any needs
- [ ] Update housekeeping slides
- [ ]  Presenter's slides
  - [ ] Request slides from presenter for _final_ accessibility check
  - [ ] Send presenter's slides to ACS

**Day of event**
- [ ] Co-orgs are in video meeting 5-10 minutes to discuss any needs/issues before the official "online" for attendees
- [ ] Coordinate with presenter
- [ ] Announcements and talk

**1-5 days after the event**
- [ ] Post-announcement, YouTube share, and thanks (MTLS)
  - [ ] Shoutout for presenter
- [ ] Finalize transcript
  - [ ] Get transcript from ACS
  - [ ] Edit transcript and push to GitHub transcript repo

**Post-event (based on team bandwidth)**
- [ ] Add transcript to YouTube video talk

**Comment by nickttng** [comment]
Closing this. Fizzled out due to weltschmerz
