### ISSUE TITLE
Much Ado About Captioning Videos - MKE

### ISSUE THREAD

**Issue by nickttng** [A11YChi/meetups-and-events#22]
**Why:** As an attendee, I want to learn about adding and creating awesome captions.

**Title:** Much Ado About Captioning Videos
**Synopsis:** Adding captions to videos is only half of the magic formula for amazing captions. The other half is quality. With more captioning DIY apps coming out, there's a lot of bad quality captions out there. In less than an hour, you'll learn why quality matters in captioning and how to create awesome captions from someone who depends on them.
**Bio:** Born hearing-free aka Deaf, Meryl depends on captions to follow the video, she has seen the best and worst of captions. Fast forward years later, her freelance digital marketing career has come in handy in educating people about captioning videos and captioning them well. Passionate about captions and accessibility, she's a frequent speaker and writer on the topic that people refer to her as the caption queen.
**Primary audience:** Digital and media creators
**When:** Thursday, Jan. 28th, 2021

---

## ToDo

**30 days before the event**
- [x] Co-org to reach out to presenter
- [x] Have a kick-off conversation
- [x] Coordinate with co-orgs for date availability
- [x] Coordinate with the presenter for next steps
  - [x] Get synopsis 
  - [x] Get bio
  - [x] Set potential dates
  - [x] Share 'Accessible Presentation' guideline
- [x] Secure ACS captioner
- [ ] Create event page/URL

**15 days before the event**
- [ ] Announce through channels (MTLS)
  - [ ] Mailing list
  - [ ] Twitter
  - [ ] LinkedIn
  - [ ] Web-A11Y Slack
- [ ] Share event page/URL with presenter
- [ ] If feasible, request (rough) slides from presenter for _initial_ accessibility check

**1-5 days before the event**
- [ ] Reminders through channels (MTLS)
  - [ ] Mailing list
  - [ ] Twitter
  - [ ] LinkedIn
  - [ ] Web-A11Y Slack
- [ ] Follow up with presenter for being online (5-10 before official "online") and any needs
- [ ] Update housekeeping slides
- [ ]  Presenter's slides
  - [ ] Request slides from presenter for _final_ accessibility check
  - [ ] Send presenter's slides to ACS
  - [ ] Upload to SpeakerDeck

**Day of event**
- [ ] Co-orgs are in video meeting 5-10 minutes to discuss any needs/issues before the official "online" for attendees
- [ ] Coordinate with presenter
- [x] Announcements and talk

**1-5 days after the event**
- [ ] Post-announcement, YouTube share, and thanks (MTLS)
  - [ ] Shoutout for presenter
- [ ] Finalize transcript
  - [ ] Get transcript from ACS
  - [ ] Edit transcript and push to GitHub transcript repo

**Post-event**
- [ ] Add/edit captions on YouTube video 
- [ ] Add transcript to YouTube video description
