### ISSUE TITLE
Protest Access - Panel

### ISSUE THREAD

**Issue by nickttng** [A11YChi/meetups-and-events#23]
**Why:** As an attendee, I want to learn about Protest Access, "a volunteer collective focused on Black Lives Matter and anti-racism related content on social media" They provide captioning, transcription, and visual descriptions as requested by online communities. (Source: [Protest Access website](https://www.protestaccess.org/))

**Title:** TBD
**Synopsis:** TBD

**Bios:**

1. **Name:** Micah Fahar, ProtestAccess co-founder, pronouns: they
    - **Bio:** Micah is a 28-year-old non-binary person living in California. They are working towards becoming a therapist and are a co-founder of Protest Access. Some of their other passions include animals, video games, singing, and other creative arts
2. **Name:** Cyril Slemaker, pronouns: he/they
    - **Bio:** Cyril is a 32-year-old, visually impaired trans man who lives in Boston. They are a former K-12 educator. As part of Protest Access, Cyril is one of the visual support mentors who helps create descriptive transcripts for Protest Access content
3. **Username:** JaxLily, pronouns: they
    - **Bio:** Jax Lily is a 28-year-old nonbinary person from CA. They are a semi-verbal autistic AAC-user, and have APD and also struggle with visual processing. They serve on the Advisory Board of Protest Access and are also working on information-related projects such as the design of our website. Outside of PA, they are in grad school studying library and information science and have a background in Deaf Education and Linguistics
4. **Name:** Jordan ("Jo") Nelson Stoeger, pronouns: she/her
    - **Bio:** Jo is a 29-year-old cis woman from Minnesota. She works as a statistician at a research university in the midwest US and volunteers at ProtestAccess as the workflow manager. Jo loves cats, the outdoors, and books!

**Audiences:** Digital accessibility, media, activism
**When:** Thursday, Jan. 14th

---

## ToDo

**30 days before the event**
- [x] Co-org to reach out to panelists
- [x] Have a kick-off conversation
- [x] Coordinate with co-orgs for date availability
- [x] Coordinate with panelists for next steps
  - [x] Get synopsis 
  - [x] Get bios
  - [x] Set potential dates
- [x] Secure ACS captioner
- [x] Create event page/URL

**15 days before the event** **(Wednesday, December 30th)**
- [ ] Announce through channels (MTLS)
  - [x] Mailing list
  - [x] Twitter
  - [ ] LinkedIn
  - [x] Web-A11Y Slack
- [x] Share event page/URL with panelists

**1-5 days before the event**
- [x] Reminders through channels (MTLS)
  - [x] Mailing list
  - [x] Twitter
  - [ ] LinkedIn
  - [x] Web-A11Y Slack
- [x] Follow up with panelists for being online (5-10 before official "online") and check for any needs
- [x] Update housekeeping slides

**Day of event**
- [x] Co-orgs are ready before Zoom opens (5-10 minutes before) to discuss any needs/issues
- [x] Coordinate with presenter
- [x] Announcements and panel talk

**1-5 days after the event**
- [ ] Post-announcement, YouTube share, and thanks (MTLS)
  - [ ] Shoutout for Protest Access
- [ ] Finalize transcript
  - [ ] Get transcript from ACS
  - [ ] Edit transcript and push to GitHub transcript repo

**Post-event**
- [ ] Add/edit captions on YouTube video 
- [ ] Add transcript to YouTube video description
