### ISSUE TITLE
[Potential] Host a social trivia night with LS

### ISSUE THREAD

**Issue by nickttng** [A11YChi/meetups-and-events#4]
**Why:** As an attendee, I want to learn more about accessibility and inclusive design facts/tips while having fun.

## ToDo

**30 days before the event**
- [ ] Have a kick-off conversation, via a video chat with Laura to ideate
  - [ ] Could this also be done remotely? 
- [ ] Coordinate with co-orgs for date availability
- [ ] Coordinate with the presenter for next steps
  - [ ] Get synopsis and bio
  - [ ] Set potential dates
  - [ ] Share 'Accessible Presentation' guideline 
- [ ] Secure a venue
- [ ] Secure ACS captioner
- [ ] Create event page/URL

**15 days before the event**
- [ ] Announce through channels (MTLS)
  - [ ] Mailing list
  - [ ] Twitter
  - [ ] LinkedIn
  - [ ] Web-A11Y Slack
- [ ] Share event page/URL with venue and presenter
- [ ] If feasible, request (rough) slides from presenter for _initial_ accessibility check

**1-5 days before the event**
- [ ] Reminders through channels (MTLS)
  - [ ] Mailing list
  - [ ] Twitter
  - [ ] LinkedIn
  - [ ] Web-A11Y Slack
- [ ] Soft check with venue for anything needed
- [ ] Follow up with presenter for time of arrival (20-30 mins before door opens) and any needs
- [ ] Update housekeeping slides
- [ ]  Presenter's slides
  - [ ] Request slides from presenter for _final_ accessibility check
  - [ ] Send presenter's slides to ACS

**Day of event**
- [ ] Bring no-photo lanyards
- [ ] Bring pronoun buttons
- [ ] Bring A/TV equipment for streaming
- [ ] Arrive 30-45 minutes before door opens (Co-orgs meet the venue team)
- [ ] Coordinate with presenter
- [ ] Announcements and talk

**1-5 days after the event**
- [ ] Post-announcement, YouTube share, and thanks (MTLS)
  - [ ] Shoutout for presenter
  - [ ] Shoutout for venue
- [ ] Finalize transcrit
  - [ ] Get transcript from ACS
  - [ ] Edit transcript and push to GitHub transcript repo
- [ ] Coordinate invoices for interpreters and sponsorship

**Post-event (based on team bandwidth)**
- [ ] Add transcript to YouTube video talk
